# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_derivList')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_derivList')
    _derivList = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_derivList', [dirname(__file__)])
        except ImportError:
            import _derivList
            return _derivList
        try:
            _mod = imp.load_module('_derivList', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _derivList = swig_import_helper()
    del swig_import_helper
else:
    import _derivList
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class DerivList(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    synced = _swig_property(_derivList.DerivList_synced_get, _derivList.DerivList_synced_set)
    derivList = _swig_property(_derivList.DerivList_derivList_get, _derivList.DerivList_derivList_set)

    def __init__(self, *args, **kwargs):
        this = _derivList.new_DerivList(*args, **kwargs)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _derivList.delete_DerivList
    __del__ = lambda self: None

    def init(self, *args, **kwargs):
        return _derivList.DerivList_init(self, *args, **kwargs)

    def clear(self, *args, **kwargs):
        return _derivList.DerivList_clear(self, *args, **kwargs)

    def sync(self, *args, **kwargs):
        return _derivList.DerivList_sync(self, *args, **kwargs)

    def get(self, *args, **kwargs):
        return _derivList.DerivList_get(self, *args, **kwargs)

    def __getitem__(self, *args):
        return _derivList.DerivList___getitem__(self, *args)

    def __setitem__(self, *args):
        return _derivList.DerivList___setitem__(self, *args)

    def help(self, *args, **kwargs):
        return _derivList.DerivList_help(self, *args, **kwargs)

class DerivListPtr(DerivList):
    def __init__(self, this):
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
        self.this.own(0)
        self.__class__ = DerivList

DerivList_swigregister = _derivList.DerivList_swigregister
DerivList_swigregister(DerivList)


pyXplorHelp = help


def help(*args):
    return _derivList.help(*args)
help = _derivList.help


