function details = importfileDenstiyFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  M4KAMBI5R1NOE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  M4KAMBI5R1NOE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  details = importfileDenstiyFile("/data2/nmr/our_algo_final/code/2m4k_ambi5r1_noe.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Jul-2022 15:24:09

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
    opts = delimitedTextImportOptions("NumVariables", 7);

    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["uplindex", "resii", "resij", "expdist", "densityi", "densityj", "densityij"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Import the data
    details = readtable(filename, opts);

    % populate other columns
    details.diffi = abs(details.densityi - details.densityij);
    details.diffj = abs(details.densityj - details.densityij);
    details.diff  = max(details.diffi, details.diffj);

end